name: tests

on:
  push:

permissions:
  contents: read
  checks: write

jobs:
  tests:
    strategy:
      matrix:
        macos: ['macos-11', 'macos-12', 'macos-13']
        include:
        - macos: 'macos-11'
          xcode-path: '/Applications/Xcode_13.2.1.app'
        - macos: 'macos-12'
          xcode-path: '/Applications/Xcode_14.2.app'
        - macos: 'macos-13'
          xcode-path: '/Applications/Xcode_15.0.1.app'

    env:
      DEVELOPER_DIR: ${{ matrix.xcode-path }}

    runs-on: ${{ matrix.macos }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: swift build -v

    - name: run unit tests
      run: swift test --parallel --xunit-output report.xml
  
    - name: report unit test results
      uses: dorny/test-reporter@afe6793191b75b608954023a46831a3fe10048d4
      if: always()
      with:
        name: 'results-unit-tests (${{ matrix.xcode }})'
        path: report.xml
        reporter: java-junit
        fail-on-error: true
